m1=int(input())
m2=int(input())
m3=int(input())
m4=int(input())
m5=int(input())
total=m1+m2+m3+m4+m5
avg=total/5
if avg >=90:
    grade="A"
elif avg >=80:
    grade="B"
elif avg >=70:
    grade="C"
elif avg >=60:
    grade="D"
else:
    grade="F"
print("Total =", total)
print("Average =", avg)
print("Grade =", grade)
